apiVersion: apps/v1
kind: Deployment
metadata:
  name: torch-inference-deployment
  labels:
    app: torch-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torch-inference
  template:
    metadata:
      labels:
        app: torch-inference
    spec:
      containers:
      - name: inference
        image: docker.io/skonto/fastapi-inference-torch
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: torch-inference-service
  labels:
    app: torch-inference
spec:
  selector:
    app: torch-inference
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
